### ISSUE TITLE
Feature request: Docs

### ISSUE THREAD

**Issue by JerryI** [AnswerDotAI/gpu.cpp#18]
Thank you for your fantastic work!
It would help a lot to new users to have docs, API documentation. For example the correspondence between C++ data types and WebGPU tensors. Which one is more optimal and some other guidelines on how to write efficient code

**Comment by austinvhuang** [comment]
Appreciate the kind words Jerryl.

Although it's not officially announced you can see a preview of the project landing page at https://gpucpp.answer.ai/ where you'll find a link to browsable API docs. Feel free to ask questions on the discord chat too https://discord.gg/zmJVhXsC7f

We have some follow-up blog posts coming up to expand on the introductory material, stay tuned!

**Comment by JerryI** [comment]
Thanks! This is what i was looking for ⚡️
