### ISSUE TITLE
No aarch64 build for libdawn.so

### ISSUE THREAD

**Issue by ghostplant** [AnswerDotAI/gpu.cpp#31]
On Linux aarch64, an improper libdawn.so for x86_64 is downloaded which is not compatible.
How to build libdawn.so for aarch64, is there a user guide or official support?

**Comment by ghostplant** [comment]
Solved by building from source, thanks!

**Comment by austinvhuang** [comment]
Nice! If you have an example repo we can reference / point others to that would be helpful.

Would love to see the Dawn project host prebuilt binaries + headers in the future.
