### ISSUE TITLE
Cannot find 'array' file of stdlib.

### ISSUE THREAD

**Issue by junjihashimoto** [AnswerDotAI/gpu.cpp#8]
It seems that -stdlib=libc++ is required on ubuntu-22.04.

```
$ clang++ -std=c++17 -I/home/junji-hashimoto/git/gpu.cpp/examples/matmul/../.. -I/home/junji-hashimoto/git/gpu.cpp/examples/matmul/../../utils -I/home/junji-hashimoto/git/gpu.cpp/examples/matmul/../../third_party/headers -L/home/junji-hashimoto/git/gpu.cpp/examples/matmul/../../third_party/lib run.cpp -ldl -ldawn -o ./build/mm
run.cpp:1:10: fatal error: 'array' file not found
#include <array>
         ^~~~~~~
1 error generated.
$ clang++ -std=c++17 -I/home/junji-hashimoto/git/gpu.cpp/examples/matmul/../.. -I/home/junji-hashimoto/git/gpu.cpp/examples/matmul/../../utils -I/home/junji-hashimoto/git/gpu.cpp/examples/matmul/../../third_party/headers -L/home/junji-hashimoto/git/gpu.cpp/examples/matmul/../../third_party/lib run.cpp -ldl -ldawn -o ./build/mm -stdlib=libc++
$ clang++ --version
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```

**Comment by austinvhuang** [comment]
This should be resolved with:

https://github.com/AnswerDotAI/gpu.cpp/commit/f983bcf5f8b37277194d5fce07d26fc8cc94cacc

For now the flag is blanket included for all builds. We may need to make some more nuanced flag decisions if we run into some ABI incompatibility issues or want to support gcc. For now let's see if we can keep the build files simple w/ clang-only support + shipping prebuilt binaries. If you (or anyone else) has a chance test on other systems to see if any issues come up.

**Comment by austinvhuang** [comment]
Reopening as I just ran into this issue testing on 22.04 but in the opposite direction. Including -stdlib=libc++ results in the error.

```
(base) austin@x1nano:~/projects/gpu.cpp$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
(base) austin@x1nano:~/projects/gpu.cpp$ clang++ --version
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by austinvhuang** [comment]
I patches this with a check:

e567c2a6dadd3057ce0de065c17ef0599f2bf522

@junjihashimoto can you check that it still works for your ubuntu builds? It's kind of a quick fix so if anyone has a better solution let me know.

**Comment by junjihashimoto** [comment]
It works on ubuntu with`-stdlib=libc++`.
It also works on nixos without`-stdlib=libc++`.
